spring:
  config:
    import: optional:file:/config/application-secret.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://{datasource-url}?serverTimezone=Asia/Seoul'
    username: '{datasource-username}'
    password: '{datasource-password}'
  sql:
    init:
      mode: never
  redis:
    host: '{redis-host}'
    port: {redis-port}
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
  mail:
    host: '{mail-host}'
    username: '{mail-username}'
    password: '{mail-password}'
    port: {mail-port}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: '{oauth2-google-client-id}'
            client-secret: '{oauth2-google-secret}'
          github:
            client-id: '{oauth2-github-client-id}'
            client-secret: '{oauth2-github-secret}'
          facebook:
            client-id: '{oauth2-facebook-client-id}'
            client-secret: '{oauth2-facebook-secret}'
          naver:
            client-id: '{oauth2-naver-client-id}'
            client-secret: '{oauth2-naver-secret}'
          kakao:
            client-id: '{oauth2-kakao-client-id}'
            client-secret: '{oauth2-kakao-secret}'
          discord:
            client-id: '{oauth2-discord-client-id}'
            client-secret: '{oauth2-discord-secret}'
          microsoft:
            client-id: '{oauth2-microsoft-client-id}'
            client-secret: '{oauth2-microsoft-secret}'
jwt:
  base64-access-secret: '{jwt-base64-access-secret}'
  base64-refresh-secret: '{jwt-base64-refresh-secret}'
  base64-register-secret: '{jwt-base64-register-secret}'
allowedOrigins: 'https://hwanstory.kr'