spring:
  profiles:
    active: local
  config:
    import: optional:file:/config/application-secret.yml
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        auto_quote_keyword: true
  servlet:
    multipart:
      enabled: true
      location: /var/attachments/temp/
      max-request-size: 100MB
      max-file-size: 100MB
  security:
    oauth2:
      client:
        registration:
          google:
            scope:
              - email
              - profile
            redirect-uri: '{baseUrl}/api/v1/authentication/oauth2/code/{registrationId}'
          github:
            redirect-uri: '{baseUrl}/api/v1/authentication/oauth2/code/{registrationId}'
          facebook:
            scope:
              - email
              - public_profile
            redirect-uri: '{baseUrl}/api/v1/authentication/oauth2/code/{registrationId}'
          naver:
            scope:
              - nickname
              - email
              - profile_image
            redirect-uri: '{baseUrl}/api/v1/authentication/oauth2/code/{registrationId}'
            client-authentication-method: post
            authorization-grant-type: authorization_code
            client-name: Naver
          kakao:
            scope:
              - profile_nickname
              - profile_image
              - account_email
            redirect-uri: '{baseUrl}/api/v1/authentication/oauth2/code/{registrationId}'
            client-authentication-method: post
            authorization-grant-type: authorization_code
            client-name: Kakao
          discord:
            scope:
              - identify
              - email
            redirect-uri: '{baseUrl}/api/v1/authentication/oauth2/code/{registrationId}'
            client-authentication-method: post
            authorization-grant-type: authorization_code
            client-name: Discord
          microsoft:
            scope:
              - https://graph.microsoft.com/User.Read
            redirect-uri: '{baseUrl}/api/v1/authentication/oauth2/code/{registrationId}'
            client-authentication-method: post
            authorization-grant-type: authorization_code
            client-name: Microsoft
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          discord:
            authorization-uri: https://discord.com/api/oauth2/authorize
            token-uri: https://discord.com/api/oauth2/token
            user-info-uri: https://discord.com/api/users/@me
            user-name-attribute: id
          microsoft:
            authorization-uri: https://login.microsoftonline.com/consumers/oauth2/v2.0/authorize
            token-uri: https://login.microsoftonline.com/consumers/oauth2/v2.0/token
            user-info-uri: https://graph.microsoft.com/v1.0/me
            user-name-attribute: id
server:
  tomcat:
    use-relative-redirects: true
  forward-headers-strategy: native
attachments:
  path: /var/attachments/